name: Update YouTube Player Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # every hour

permissions:
  contents: write
  pull-requests: write

jobs:
  check-player:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install UV & deps
        run: |
          pip install uv
          uv sync

      - name: Snapshot before (dirs only)
        run: |
          find . -maxdepth 1 -mindepth 1 -type d -not -path "*/\.*" -printf "%f\n" | sort > before.txt

      - name: Fetch and build JS
        run: uv run workflow.py

      - name: Snapshot after (dirs only)
        run: |
          find . -maxdepth 1 -mindepth 1 -type d -not -path "*/\.*" -printf "%f\n" | sort > after.txt

      - name: Detect new directory
        id: detect
        run: |
          NEW_DIR=$(comm -13 before.txt after.txt | head -n1)
          if [ -z "$NEW_DIR" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "player_id=$NEW_DIR"  >> $GITHUB_OUTPUT
          echo "branch=update-player-$NEW_DIR" >> $GITHUB_OUTPUT
          echo "New player detected: $NEW_DIR"

      - name: Skip if nothing new
        if: steps.detect.outputs.skip == 'true'
        run: echo "Nothing to update."

      - name: Debug file listing
        if: steps.detect.outputs.skip != 'true'
        run: |
          PLAYER_ID="${{ steps.detect.outputs.player_id }}"
          echo "New directory contents:"
          ls -la "$PLAYER_ID"

      - name: Configure Git
        if: steps.detect.outputs.skip != 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check remote branch
        if: steps.detect.outputs.skip != 'true'
        id: branch-check
        run: |
          if git ls-remote --heads origin "${{ steps.detect.outputs.branch }}" | grep -q .; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Abort if branch exists
        if: steps.branch-check.outputs.exists == 'true'
        run: echo "Branch ${{ steps.detect.outputs.branch }} already exists, skipping."

      - name: Create branch, commit & push
        if: steps.branch-check.outputs.exists == 'false'
        run: |
          BR=${{ steps.detect.outputs.branch }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BR"
          # remove snapshot files so they don’t get added
          rm -f before.txt after.txt
          # add only the new dir
          git add "$NEW_DIR"
          git commit -m "chore: update YouTube player script for $NEW_DIR"
          git push --set-upstream origin "$BR"

      - name: Create Pull Request
        if: steps.detect.outputs.skip != 'true' && steps.branch-check.outputs.exists == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: dev
          branch: ${{ steps.detect.outputs.branch }}
          title: "Update player script: ${{ steps.detect.outputs.player_id }}"
          commit-message: "chore: update YouTube player script for ${{ steps.detect.outputs.player_id }}"
          body: |
            This PR updates the YouTube decryption script for player ID `${{ steps.detect.outputs.player_id }}`.
            - Generated on ${{ github.run_date }}
            - Includes the new `base.js` bundle.
          labels: automated
